fix bug proceed data lead to customer and rilis version 1.0.3
orangerdev/sejoli-lead-gen pull request #8
Opened 2024-03-18 07:07 UTC by asdzakky

2024-03-18 07:30 UTC, orangerdev requested changes

2024-03-18 07:30 UTC, orangerdev commented on inc/show-forms-backend.php
mas, jangan jadi spaghetti code ya

maksudnya ini disini htmlnya dicampur, better di include saja filenya untuk rendering html, kemudian pakai ob_start dan ob_get_contens. 

prinsip code yang baik itu mudah dibaca dan yang pasti bisa di-linter

2024-03-18 07:30 UTC, orangerdev commented on inc/show-lead.php
>                  $thHead = '<div class="wrap" id="form-leads-show"><table class="show-leads-table wp-list-table widefat " style="width: 100%" id="show-leads-table" >
ini juga mas, lebih baik dipisah jadi 1 file khusus untuk templatingnya

2024-03-18 07:30 UTC, orangerdev commented on inc/show-lead.php
>                  $thHead = '<div class="wrap" id="form-leads-show"><table class="show-leads-table wp-list-table widefat " style="width: 100%" id="show-leads-table" >
ini juga

2024-03-20 04:25 UTC, asdzakky commented
feedback done pak @orangerdev

2024-03-21 23:09 UTC, orangerdev requested changes

2024-03-21 23:09 UTC, orangerdev commented on template/front-end-form.php
> +echo '<div class="leadform-show-form-'.$this_form_id.' leadform-show-form '.$this_form_size.' lf-form-default leadform-lite"><div class="lead-head"></div>'.$captcha_script.'
?>
<div class="leadform-show-form-<?= $this_form_id; ?>'>

2024-03-22 00:14 UTC, asdzakky commented on template/front-end-form.php
> +echo '<div class="leadform-show-form-'.$this_form_id.' leadform-show-form '.$this_form_size.' lf-form-default leadform-lite"><div class="lead-head"></div>'.$captcha_script.'
yg ini knp ya pak @orangerdev ?

2024-03-24 03:18 UTC, orangerdev approved these changes

2024-03-24 03:19 UTC, merged